# Generated by Django 4.1.2 on 2022-10-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatRoom',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
