# Generated by Django 4.1.2 on 2022-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='a', max_length=120),
            preserve_default=False,
        ),
    ]
